gcp:
  project_id: "your-gcp-project-id"
  bucket_name: "netflix_movies_details"
  dataset: "netflix_movies_dataset" 
  credentials_file: "config/gcp_credentials.json"

paths:
  raw_data: "gs://netflix_movies_detailed/raw/"
  processed_data: "gs://netflix_movies_detailed/processed/"
